fix: add control table update workflow

diff --git a/.github/workflows/etl.yml b/.github/workflows/etl.yml
--- a/.github/workflows/etl.yml
+++ b/.github/workflows/etl.yml
@@ -150,6 +150,27 @@ jobs:
       - name: Display structure of downloaded files
         run: ls -R
         working-directory: control_change_log
+      - name: Update Control Table
+        run: python update_control_table.py 20 control_change_log data/latest.control
+        working-directory: control_change_log
+      - name: Git commit
+        run: |
+          git config --global user.name "jeffrey82221"
+          git config --global user.email "jeffrey82221@gmail.com"
+          git add data/latest.control
+          git diff-index --quiet HEAD || git commit -m 'update: control table'
+      - name: Git pull
+        run: |
+          git config --global user.email "jeffrey82221@gmail.com"
+          git config --global user.name "jeffrey82221"
+          git config --global http.postBuffer 1048576000
+          git config pull.rebase false
+          git pull origin main || echo 'pull failed'
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.PERSONAL_TOKEN }}
+          branch: main
   update_release_time:
     name: Do Release Time Table ETL
     needs: apply_control_table_change
