Update etl.yml

diff --git a/.github/workflows/etl.yml b/.github/workflows/etl.yml
--- a/.github/workflows/etl.yml
+++ b/.github/workflows/etl.yml
@@ -103,4 +103,69 @@ jobs:
         with:
           github_token: ${{ secrets.PERSONAL_TOKEN }}
           branch: main
-
+  update_repo_info:
+    name: Update Repo Info Json
+    needs: list_latest_json
+    uses: ./.github/workflows/etl_parallel.yml
+    with: 
+      split_cnt: 50
+      branch_title: update_repo_info
+      max-parallel: 5
+      package-install-command: |
+        pip install requests==2.28.2
+        pip install tqdm
+        pip install pypistats==1.1.0
+        pip install toolz
+        pip install cytoolz==0.12.1
+        pip install httpx==0.23.0
+      main-python-file: update_repo_info_all.py
+      input-menu-file: data/latest.menu
+      git-add-command: git add data/fork data/repo data/star data/watcher etag/
+    secrets:
+      pat: ${{ secrets.PERSONAL_TOKEN }}
+      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+  merge_repo_infos:
+    name: Merge Infos 
+    needs: update_repo_info
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        split_cnt: [50]
+    steps:
+      - name: checkout 
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 1
+          ref: 'main'
+          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
+          ssh-known-hosts: github.com
+      - name: Download Jsonls
+        uses: actions/download-artifact@v3
+        with:
+          path: download
+      - name: Display structure of downloaded files
+        run: ls -R
+        working-directory: download
+      - name: Merge jsonl
+        run: |
+          rm -f data/repo_info.jsonl
+          end=$((${{ matrix.split_cnt }}-1))
+          echo "end=$end"
+          cat download/{0..end}/info.jsonl >> data/repo_info.jsonl
+      - name: Git commit
+        run: |
+          git config --global user.name "jeffrey82221"
+          git config --global user.email "jeffrey82221@gmail.com"
+          git add data/repo_info.jsonl
+          git diff-index --quiet HEAD || git commit -m 'update: email content'
+      - name: Git pull
+        run: |
+          git config --global user.email "jeffrey82221@gmail.com"
+          git config --global user.name "jeffrey82221"
+          git config pull.rebase false
+          git pull origin main || echo 'pull failed'
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.PERSONAL_TOKEN }}
+          branch: main
